Repository afar-cmyk/ProyectoBibliotech, pull requests merged in 2021-09, with the labels that each got.

#33 Login#21 into main
  BibliotechWeb/login.html
  BibliotechWeb/styles/login-estilosmaterial.css
  BibliotechWeb/styles/login.css
  BibliotechWeb/styles/style-login.css
Labels: desarrollo

#48 Bugfix Login.html
  .vscode/settings.json
  BibliotechWeb/login.html
  BibliotechWeb/styles/style-login.css
Labels: bug

#50 Portal Administrativo - Updated
  .vscode/settings.json
  BibliotechWeb/admin.html
  BibliotechWeb/item.html
  BibliotechWeb/login.html
  BibliotechWeb/newer.html
  BibliotechWeb/scripts/navegacion.js
  BibliotechWeb/styles/style-admin.css
  BibliotechWeb/styles/style-item.css
  BibliotechWeb/styles/style-newer.css
Labels: frontend, desarrollo, Prioritario

#57 Portal Administrativo Update #3
  .gitignore
  .vscode/settings.json
  BibliotechWeb/admin.html
  BibliotechWeb/item.html
  BibliotechWeb/newer.html
  BibliotechWeb/styles/style-admin.css
  BibliotechWeb/styles/style-edit_admin.css
  BibliotechWeb/styles/style-edit_item.css
  BibliotechWeb/styles/style-item.css
  BibliotechWeb/styles/style-new_admin.css
  BibliotechWeb/styles/style-new_item.css
  BibliotechWeb/styles/style-newer.css
  DOCUMENTACION SPRINT 0/Instalación_entorno_desarrollo - Proy BIBLIOTECH.pdf
  DOCUMENTACION SPRINT 0/Product_Backlog BIBLIOTECH 07SEPT21.xlsx
  README.md
  bibliotech/.editorconfig
  bibliotech/.gitignore
  bibliotech/README.md
  bibliotech/babel.config.js
  bibliotech/package-lock.json
  bibliotech/package.json
  bibliotech/public/favicon.ico
  bibliotech/public/index.html
  bibliotech/src/App.vue
  bibliotech/src/assets/logo.png
  bibliotech/src/components/HelloWorld.vue
  bibliotech/src/main.js
  bibliotech/src/router/index.js
  bibliotech/src/store/index.js
  bibliotech/src/views/About.vue
  bibliotech/src/views/Home.vue
  images/LOGOTIPO-PEQUENO.png
Labels: frontend, gestión, backend, desarrollo, Prioritario

#58 Api#4
  apiRest/.gitignore
  apiRest/app.js
  apiRest/package-lock.json
  apiRest/package.json
Labels: mejora, backend
